apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-python
  labels:
    app: example-python
spec:
  selector:
    matchLabels:
      app: example-python
  template:
    metadata:
      labels:
        app: example-python
    spec:
      containers:
        - name: example-python
          image: user632716/general:example-python-image
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
