apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-python
  labels:
    app: example-python
spec:
  selector:
    matchLabels:
      app: example-python
  template:
    metadata:
      labels:
        app: example-python
    spec:
      containers:
        - name: example-python
          image: user632716/general:example-python-image
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_PASSWORD
              value: pgpassword
            - name: POSTGRES_HOST
              value: postgres-external
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
